use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub enum Ecosystem {
    Node,
    Python,
    Rust,
    Java,
    DotNet,
    Go,
    Ruby,
    Docker,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub enum PackageManager {
    Npm,
    Pnpm,
    Yarn,
    Bun,
    Pip,
    Poetry,
    Pipenv,
    Uv,
    Cargo,
    Maven,
    Gradle,
    DotNet,
    GoModules,
    Bundler,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub enum Runtime {
    Node,
    Python,
    Rust,
    Go,
}

/// A runtime version a project asks for, and the file that says so.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct RuntimeRequirement {
    pub runtime: Runtime,
    /// As written in the file, e.g. `>=18`, `3.12`, `1.85`.
    pub version: String,
    pub source: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub enum ArtifactKind {
    NodeModules,
    PythonVenv,
    PythonToolCache,
    CargoTarget,
    GradleBuild,
    GradleProjectCache,
    DotNetBuild,
    NextBuild,
}

impl ArtifactKind {
    /// How the folder is recreated.
    pub fn restored_by(self) -> &'static str {
        match self {
            Self::NodeModules => "reinstalled by npm, pnpm or Yarn from the lockfile",
            Self::PythonVenv => "recreated with python -m venv and a reinstall of the requirements",
            Self::PythonToolCache => "regenerated automatically by the tool",
            Self::CargoTarget => "rebuilt by cargo build",
            Self::GradleBuild => "rebuilt by Gradle",
            Self::GradleProjectCache => "regenerated by Gradle",
            Self::DotNetBuild => "rebuilt by dotnet build",
            Self::NextBuild => "rebuilt by next build",
        }
    }
}

/// A folder inside a project that its tools can recreate.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct Artifact {
    pub kind: ArtifactKind,
    pub path: String,
    /// Space used on disk; `null` if it was not measured.
    #[ts(type = "number | null")]
    pub bytes: Option<u64>,
    pub restored_by: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct Project {
    pub path: String,
    /// From the project file when it declares one, otherwise the folder name.
    pub name: String,
    pub ecosystems: Vec<Ecosystem>,
    pub package_managers: Vec<PackageManager>,
    /// Marker files found, e.g. `package.json`, `pnpm-lock.yaml`.
    pub markers: Vec<String>,
    pub runtimes: Vec<RuntimeRequirement>,
    pub git: bool,
    /// Newest change among the project's top-level files and folders (artifact folders
    /// excluded) and Git metadata. An approximation of when it was last worked on.
    #[ts(type = "number | null")]
    pub last_activity_ms: Option<i64>,
    /// Space used by the whole project folder, artifacts included.
    #[ts(type = "number | null")]
    pub total_bytes: Option<u64>,
    pub artifacts: Vec<Artifact>,
    /// Project files that could not be read or parsed.
    pub warnings: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct Detection {
    pub root: String,
    pub projects: Vec<Project>,
    #[ts(type = "number")]
    pub folders_visited: u64,
    /// A depth or folder limit was reached, so some projects may be missing.
    pub truncated: bool,
    pub cancelled: bool,
    pub errors: Vec<String>,
    #[ts(type = "number")]
    pub elapsed_ms: u64,
}
