// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactKind } from "./ArtifactKind";

/**
 * A folder inside a project that its tools can recreate.
 */
export type Artifact = { kind: ArtifactKind, path: string, 
/**
 * Space used on disk; `null` if it was not measured.
 */
bytes: number | null, restoredBy: string, };
