// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArtifactKind = "nodeModules" | "pythonVenv" | "pythonToolCache" | "cargoTarget" | "gradleBuild" | "gradleProjectCache" | "dotNetBuild" | "nextBuild";
