// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CachedArtifact } from "./CachedArtifact";
import type { GroupSize } from "./GroupSize";

export type ArtifactCache = { root: string, totalBytes: number, artifactVersions: number, 
/**
 * Largest groups first (top 20).
 */
groups: Array<GroupSize>, 
/**
 * Largest artifacts first (at most 300).
 */
artifacts: Array<CachedArtifact>, 
/**
 * Artifacts not listed individually.
 */
artifactsNotListed: number, 
/**
 * Artifacts with more than one version cached.
 */
multiVersionArtifacts: number, 
/**
 * Bytes in versions other than each artifact's most recently downloaded one.
 */
olderVersionsBytes: number, 
/**
 * Maven `*.lastUpdated` markers left by failed downloads.
 */
failedDownloads: number, truncated: boolean, };
