// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuditIntegrity = { records: number, intact: boolean, firstBadSeq: number | null, problem: string | null, };
