// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Approval } from "./Approval";
import type { AuditKind } from "./AuditKind";
import type { Outcome } from "./Outcome";

export type AuditEntry = { seq: number, atMs: number, operationId: string, kind: AuditKind, provider: string | null, user: string, items: number, bytes: number, policy: string, approval: Approval, outcome: Outcome, errors: Array<string>, details: Record<string, unknown>, hash: string, };
