// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CachedVersion } from "./CachedVersion";

export type CachedArtifact = { group: string, artifact: string, 
/**
 * Most recently downloaded first.
 */
versions: Array<CachedVersion>, bytes: number, };
