// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CachedVersion = { version: string, bytes: number, 
/**
 * Newest file time in the version folder: when it was downloaded, not last used.
 */
downloadedMs: number | null, 
/**
 * Projects that name this exact version directly.
 */
declaredBy: Array<string>, };
