// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Category = "windows" | "applications" | "developerTools" | "developerDependencies" | "packageCaches" | "buildArtifacts" | "containers" | "wsl" | "browsers" | "games" | "logs" | "temporaryFiles" | "userData" | "unknown";
