// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";

/**
 * Why a path was put in a category.
 */
export type Classification = { category: Category, rule: string, reason: string, };
