// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";

/**
 * Error returned by fallible IPC commands. `message` is written for end users.
 */
export type CommandError = { kind: ErrorKind, message: string, };
