// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The verdict for one candidate.
 */
export type Decision = { "state": "eligible" } | { "state": "tooRecent", newestModifiedMs: number, } | { "state": "protected", reason: string, } | { "state": "skipped", reason: string, };
