// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Project } from "./Project";

export type Detection = { root: string, projects: Array<Project>, foldersVisited: number, 
/**
 * A depth or folder limit was reached, so some projects may be missing.
 */
truncated: boolean, cancelled: boolean, errors: Array<string>, elapsedMs: number, };
