// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeStatus } from "./NodeStatus";

export type DirChild = { id: number, name: string, totalBytes: number, fileCount: number, hasChildren: boolean, status: NodeStatus, };
