// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Classification } from "./Classification";
import type { Crumb } from "./Crumb";
import type { DirChild } from "./DirChild";
import type { NodeStatus } from "./NodeStatus";
import type { ScanRef } from "./ScanRef";

/**
 * One level of a saved scan.
 */
export type DirListing = { scanId: number, node: number, crumbs: Array<Crumb>, totalBytes: number, 
/**
 * Bytes in files directly inside this folder (not in subfolders).
 */
filesBytes: number, filesHere: number, status: NodeStatus, classification: Classification | null, children: Array<DirChild>, 
/**
 * Subfolders not listed: too small to store, or beyond the listing limit.
 */
hiddenChildren: number, hiddenBytes: number, 
/**
 * The analysis this listing is compared with, if any.
 */
comparedTo: ScanRef | null, 
/**
 * This folder's size in that analysis, if it was stored there.
 */
previousTotalBytes: number | null, };
