// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Crumb } from "./Crumb";
import type { DirChild } from "./DirChild";
import type { NodeStatus } from "./NodeStatus";

/**
 * One level of a finished scan.
 */
export type DirListing = { scanId: number, node: number, path: string, crumbs: Array<Crumb>, totalBytes: number, 
/**
 * Bytes in files directly inside this folder (not in subfolders).
 */
filesBytes: number, filesHere: number, status: NodeStatus, children: Array<DirChild>, 
/**
 * Subfolders not listed because of [`MAX_CHILDREN`].
 */
hiddenChildren: number, hiddenBytes: number, };
