// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a drive's free space changed over the recorded window.
 */
export type DriveTrend = { root: string, 
/**
 * When the earliest snapshot in the window was taken.
 */
sinceMs: number, 
/**
 * Latest free space minus earliest; negative means the drive filled up.
 */
freeChangeBytes: number, samples: number, };
