// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DriveKind } from "./DriveKind";
import type { DriveStatus } from "./DriveStatus";
import type { Space } from "./Space";

export type Drive = { 
/**
 * Root path, e.g. `C:\`.
 */
root: string, kind: DriveKind, label: string | null, fileSystem: string | null, space: Space | null, 
/**
 * The volume Windows is installed on.
 */
isSystem: boolean, status: DriveStatus, };
