// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EntryStatus = { "state": "pending" } | { "state": "quarantined" } | { "state": "restored" } | { "state": "purged" } | { "state": "skipped", reason: string, } | { "state": "failed", reason: string, };
