// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactCache } from "./ArtifactCache";
import type { GradleVersionUse } from "./GradleVersionUse";
import type { GroupSize } from "./GroupSize";

export type GradleHome = { root: string, totalBytes: number, modules: ArtifactCache | null, 
/**
 * Wrapper distributions and per-Gradle-version caches.
 */
versions: Array<GradleVersionUse>, 
/**
 * Other shared cache folders (transforms, build cache, jars) with sizes.
 */
shared: Array<GroupSize>, };
