// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GradleVersionUse = { version: string, 
/**
 * What this entry is, e.g. "wrapper distribution (bin)" or "per-version cache".
 */
what: string, path: string, bytes: number, 
/**
 * Searched projects whose wrapper uses this Gradle version.
 */
usedBy: Array<string>, };
