// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactCache } from "./ArtifactCache";
import type { GradleHome } from "./GradleHome";

export type JvmAnalysis = { maven: ArtifactCache | null, gradle: GradleHome | null, 
/**
 * Projects whose build files were read for declared versions.
 */
projectsRead: number, warnings: Array<string>, };
