// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Classification } from "./Classification";

/**
 * One of a saved analysis's largest files, with its classification.
 */
export type LargeFileView = { path: string, bytes: number, logicalBytes: number, classification: Classification | null, };
