// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryStatus } from "./EntryStatus";
import type { ItemKind } from "./ItemKind";

export type ManifestEntry = { index: number, originalPath: string, kind: ItemKind, bytes: number, files: number, status: EntryStatus, };
