// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManifestEntry } from "./ManifestEntry";

export type Manifest = { version: number, operationId: string, provider: string, user: string, createdAtMs: number, expiresAtMs: number, entries: Array<ManifestEntry>, };
