// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkKind } from "./LinkKind";
import type { NotScannedReason } from "./NotScannedReason";

export type NodeStatus = { "state": "complete" } | { "state": "accessDenied" } | { "state": "error", message: string, } | { "state": "link", kind: LinkKind, } | { "state": "excluded" } | { "state": "notScanned", reason: NotScannedReason, };
