// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviewItem } from "./PreviewItem";
import type { ProviderInfo } from "./ProviderInfo";
import type { RootReport } from "./RootReport";

export type Preview = { provider: ProviderInfo, 
/**
 * Always true: nothing was changed to produce this preview.
 */
dryRun: boolean, generatedAtMs: number, roots: Array<RootReport>, 
/**
 * Largest first.
 */
items: Array<PreviewItem>, eligibleBytes: number, eligibleFiles: number, eligibleItems: number, 
/**
 * The preview stopped early (cancelled or hit an entry limit); totals are partial.
 */
incomplete: boolean, };
