// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Preview } from "./Preview";

/**
 * A preview plus where it was recorded in the audit log.
 */
export type PreviewResponse = { preview: Preview, operationId: string, 
/**
 * Audit sequence number; `null` if the audit record could not be written.
 */
auditSeq: number | null, };
