// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Decision } from "./Decision";
import type { ItemKind } from "./ItemKind";

export type PreviewItem = { path: string, kind: ItemKind, 
/**
 * Space used on disk (allocated bytes) by the item and everything inside it.
 */
bytes: number, files: number, 
/**
 * Newest modification time found in the item, Unix ms.
 */
newestModifiedMs: number | null, decision: Decision, };
