// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Artifact } from "./Artifact";
import type { Ecosystem } from "./Ecosystem";
import type { PackageManager } from "./PackageManager";
import type { RuntimeRequirement } from "./RuntimeRequirement";

export type Project = { path: string, 
/**
 * From the project file when it declares one, otherwise the folder name.
 */
name: string, ecosystems: Array<Ecosystem>, packageManagers: Array<PackageManager>, 
/**
 * Marker files found, e.g. `package.json`, `pnpm-lock.yaml`.
 */
markers: Array<string>, runtimes: Array<RuntimeRequirement>, git: boolean, 
/**
 * Newest change among the project's top-level files and folders (artifact folders
 * excluded) and Git metadata. An approximation of when it was last worked on.
 */
lastActivityMs: number | null, 
/**
 * Space used by the whole project folder, artifacts included.
 */
totalBytes: number | null, artifacts: Array<Artifact>, 
/**
 * Project files that could not be read or parsed.
 */
warnings: Array<string>, };
