// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Detection } from "./Detection";

/**
 * The latest search of one folder.
 */
export type ProjectSearch = { root: string, searchedAtMs: number, detection: Detection, };
