// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A location Sentinel will never modify, with the reason it is protected.
 */
export type ProtectedLocation = { path: string, reason: string, };
