// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { Risk } from "./Risk";

/**
 * What a provider cleans and why it is considered removable.
 */
export type ProviderInfo = { id: string, name: string, category: Category, risk: Risk, 
/**
 * What the items are.
 */
description: string, 
/**
 * What happens if they are removed, and whether they come back.
 */
onRemoval: string, 
/**
 * Items with anything modified more recently than this are never eligible.
 */
minAgeDays: number, 
/**
 * False for analysis-only providers: they are previewed but nothing is ever
 * eligible, and the executor refuses them.
 */
canClean: boolean, 
/**
 * Why an analysis-only provider cannot clean, or other context worth showing.
 */
note: string | null, };
