// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Manifest } from "./Manifest";

export type QuarantineContents = { root: string, 
/**
 * Newest first.
 */
operations: Array<Manifest>, 
/**
 * Operation folders whose record could not be read.
 */
problems: Array<string>, };
