// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Risk shown to users; mirrors [`RiskLevel`].
 */
export type Risk = "safe" | "lowRisk" | "mediumRisk" | "highRisk" | "protected";
