// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RootReport = { "state": "scanned", path: string, } | { "state": "missing", path: string, } | { "state": "unavailable", path: string, reason: string, };
