// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Runtime } from "./Runtime";

/**
 * A runtime version a project asks for, and the file that says so.
 */
export type RuntimeRequirement = { runtime: Runtime, 
/**
 * As written in the file, e.g. `>=18`, `3.12`, `1.85`.
 */
version: string, source: string, };
