// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanRef } from "./ScanRef";
import type { ScanStats } from "./ScanStats";

/**
 * A scan saved in the local database.
 */
export type SavedScan = { scanId: number, root: string, finishedAtMs: number, stats: ScanStats, 
/**
 * Folders smaller than this were not stored individually.
 */
minFolderBytes: number, previous: ScanRef | null, };
