// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScanStats = { dirs: number, files: number, totalBytes: number, totalLogicalBytes: number, accessDenied: number, errors: number, linksSkipped: number, excluded: number, 
/**
 * The user cancelled; totals are a lower bound.
 */
cancelled: boolean, 
/**
 * A depth or entry budget was hit; totals are a lower bound.
 */
truncated: boolean, elapsedMs: number, };
