// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanProgress } from "./ScanProgress";

export type ScanProgressEvent = { 
/**
 * Id of the running job (used to cancel it).
 */
id: number, root: string, progress: ScanProgress, };
