// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanFinishedEvent } from "./ScanFinishedEvent";
import type { ScanProgressEvent } from "./ScanProgressEvent";

export type ScanStatus = { running: ScanProgressEvent | null, last: ScanFinishedEvent | null, };
