// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScanProgress = { dirs: number, files: number, bytes: number, 
/**
 * Directories that could not be read.
 */
problems: number, };
