// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SavedScan } from "./SavedScan";

export type ScanFinishedEvent = { id: number, scan: SavedScan, };
