// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Capacity figures for a volume. All values in bytes.
 */
export type Space = { totalBytes: number, usedBytes: number, 
/**
 * Free space on the volume.
 */
freeBytes: number, 
/**
 * Free space usable by the current user (smaller than `free_bytes` under quotas).
 */
availableBytes: number, 
/**
 * Less than [`LOW_SPACE_PERCENT`] of the volume is free.
 */
lowSpace: boolean, };
